"""Plain-language descriptions of orders, and the error analysis built from them."""
from __future__ import annotations

import pandas as pd

from src.load import PRICE_SCALE

ROLE_NAMES = {"spoof": "injected spoof", "hard_neg": "hard negative (price moved away, then cancelled)",
              "orig": "original order from the real data", "genuine": "the spoofer's own filled order"}
REASON_NAMES = {"timer": "cancelled after a fixed hold", "after_fill": "cancelled right after its own fill",
                "approach": "cancelled as the best price came toward it",
                "moved_away": "cancelled after the price moved away"}


def clock(seconds: float) -> str:
    return (pd.Timestamp(0) + pd.to_timedelta(seconds, unit="s")).strftime("%H:%M:%S.%f")[:-3]


def life_story(order: pd.Series) -> str:
    """One paragraph: what the order was, how it ended, what the market did meanwhile."""
    side = "buy" if order.direction == 1 else "sell"
    how = {"deleted": "cancelled", "filled": "fully executed", "open": "still resting at the close"}[order.status]
    lived = f" after {order.lifetime_s:.2f} seconds" if pd.notna(order.lifetime_s) else ""
    text = (f"A {side} order for {order.size_add:,.0f} shares at ${order.price / PRICE_SCALE:.2f} "
            f"(larger than {order.size_pct:.1%} of that day's orders, {order.depth_share_add:.0%} of the visible "
            f"depth on its side, {order.dist_ticks:.0f} ticks from the best price) was added at "
            f"{clock(order.t_add)}. It was {how}{lived} with {order.fill_ratio:.0%} filled. While it rested, "
            f"{order.opp_exec_qty:,.0f} shares traded on the opposite side and the mid price moved "
            f"{order.mid_move_bps:+.2f} bps in the direction its pressure would push.")
    if pd.notna(order.dist_change_ticks) and order.status == "deleted":
        moved = ("had not moved relative to it" if order.dist_change_ticks == 0 else
                 f"had moved {abs(order.dist_change_ticks):.0f} tick{'' if abs(order.dist_change_ticks) == 1 else 's'} "
                 f"{'away from' if order.dist_change_ticks > 0 else 'toward'} it")
        text += f" When it was cancelled the best price {moved}."
    if order.ep_n_orders > 1:
        text += (f" It belongs to a group of {order.ep_n_orders:.0f} large unfilled cancels on the same side, "
                 f"{order.ep_cancel_together:.0f} of them cancelled at the same moment.")
    return text


def error_cases(test: dict[str, pd.DataFrame], detector, n: int = 5) -> list[dict]:
    """The detector's worst mistakes: top-ranked non-spoofs and lowest-ranked spoofs."""
    frames = []
    for ticker, orders in test.items():
        scored = orders[orders.role != "genuine"].copy()
        scored["rank"] = scored[f"score_{detector.name}"].rank(ascending=False, method="first").astype(int)
        frames.append(scored)
    everything = pd.concat(frames)
    picks = {"false positive": everything[everything.label == 0].nsmallest(n, "rank"),
             "missed spoof": everything[everything.label == 1].nlargest(n, "rank")}
    cases = []
    for kind, rows in picks.items():
        shap = detector.shap_values(rows)
        for (order_id, o), (_, contrib) in zip(rows.iterrows(), shap.iterrows()):
            strongest = contrib.abs().sort_values(ascending=False).index[:5]
            cases.append({
                "kind": kind, "ticker": o.ticker, "order_id": int(order_id), "rank": int(o["rank"]),
                "of": int((everything.ticker == o.ticker).sum()), "truth": ROLE_NAMES[o.role],
                "reason": REASON_NAMES.get(o.reason, ""), "story": life_story(o),
                "shap": [{"feature": f, "value": float(o[f]), "push": float(contrib[f])} for f in strongest]})
    return cases


def error_markdown(cases: list[dict]) -> str:
    lines = ["# Error analysis: LightGBM on the unseen test days", "",
             "Generated by `python -m src.run`. SHAP pushes are in log-odds; positive = more suspicious.", ""]
    for kind, title in (("false positive", "Top-ranked alerts that are not injected spoofs"),
                        ("missed spoof", "Injected spoofs ranked lowest")):
        lines += [f"## {title}", ""]
        for c in (c for c in cases if c["kind"] == kind):
            truth = c["truth"] + (f", {c['reason']}" if c["reason"] else "")
            lines += [f"### {c['ticker']} order {c['order_id']}: rank {c['rank']:,} of {c['of']:,}", "",
                      f"Truth: {truth}.", "", c["story"], "", "| Feature | Value | SHAP push |", "|---|---|---|"]
            lines += [f"| `{s['feature']}` | {s['value']:.3g} | {s['push']:+.2f} |" for s in c["shap"]]
            lines.append("")
    return "\n".join(lines)
